
[NoDelete]
interface BumpArrayInternal {
    [Static, Internal="BumpArrayInternal_getAsDynamic"] dynamic getAsDynamic(VoidPtr array, int element);
};

[NoDelete]
interface BumpCompactArrayInternal {

    [Static, Internal="BumpCompactArrayInternal_getAsDynamic"] dynamic getAsDynamic(VoidPtr array, int element);
};

interface BumpAllocatorInternal {
    void BumpAllocatorInternal( int sizeInBytes );

    dynamic alloc( type t );
    VoidPtr allocArray( type t, int count );
    VoidPtr allocCompactArray( type t, int count );

    int totalBytes();
    int availableBytes();
    int allocatedBytes();

    void clear();
    void dispose();
};

